x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 5s
  retries: 5

services:

  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      pushgateway: *healthy
    environment:
      PUSHGATEWAY: http://pushgateway:9091

  pushgateway:
    image: prom/pushgateway
    command:
      - --web.enable-admin-api
    ports:
      - 9091:9091
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

volumes:
  gem_cache:
